name: Deploy via SSH (rsync) to Lolipop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Lolipop
        uses: easingthemes/ssh-deploy@main
        with:
          # SSH接続情報
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PASS }} # パスワードを鍵として代用する設定です
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: 2222 # ロリポップ専用ポート
          
          # ⚠️ 転送元（GitHub）
          SOURCE: "./"
          # ⚠️ 転送先（サーバー上の絶対パス）
          # SSHでは /home/users/... から始まるフルパスが必要です
          TARGET: "/home/users/2/sub.jp-houseinfo/web/fukunaga/wp-content/themes/mytheme/"
          
          # 不要なファイルを送らない設定
          EXCLUDE: "/.git/, /.github/"
